### ISSUE TITLE
Error with Python 3.6.0 [BUG]

### ISSUE THREAD

**Issue by resparis** [willmcgugan/rich#215]
Using Python 3.6.0 from Anaconda, I am getting the following error when I tried to import it.

>>> console = Console()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'Console' is not defined
>>> from rich.console import Console
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "\project\rich\lib\site-packages\rich\console.py", line 30, in <module>
    from . import errors, themes
  File "project\rich\lib\site-packages\rich\themes.py", line 1, in <module>
    from .default_styles import DEFAULT_STYLES
  File "\project\rich\lib\site-packages\rich\default_styles.py", line 18, in <module>
    strike=False,
  File "\project\rich\lib\site-packages\rich\style.py", line 115, in __init__
    self._color = None if color is None else _make_color(color)
  File "\project\rich\lib\site-packages\rich\style.py", line 113, in _make_color
    return color if isinstance(color, Color) else Color.parse(color)
AttributeError: type object 'Color' has no attribute 'parse'

**Comment by willmcgugan** [comment]
Rich [requires](https://rich.readthedocs.io/en/latest/introduction.html#requirements) Python 3.6.1 or above.

**Comment by daniellivingston** [comment]
@willmcgugan Sorry for dragging this issue from the grave, but has there been a Rich release that does work with 3.6.0? I'm working with a project that, unfortunately, has a hard 3.6.0 version lock.

**Comment by willmcgugan** [comment]
I don't *think* so. If there it is very old.
